import {
  htmlimage,
  cssimage,
  jsimage,
  reactimage,
  nodeimage,
  mongodbimage,
  tailwindimage,
  gitimage,
  nextjsimage,
  bootstrapimage,
  reduximage,
  excelimage,
  githubimage,
  jwtimage,
  jsonimage,
  restfulapiimage,
  socketioimage,
  vscodeimage,
} from "../components/Images";

const skillsDetails = [
  { name: "HTML", image: htmlimage },
  { name: "CSS", image: cssimage },
  { name: "JavaScript", image: jsimage },
  { name: "React", image: reactimage },
  { name: "Node.js", image: nodeimage },
  { name: "MongoDB", image: mongodbimage },
  { name: "Tailwind CSS", image: tailwindimage },
  { name: "Git", image: gitimage },
  { name: "Redux", image: reduximage },
  { name: "Excel", image: excelimage },
  { name: "GitHub", image: githubimage },
  { name: "JWT", image: jwtimage },
  { name: "JSON", image: jsonimage },
  { name: "RESTful API", image: restfulapiimage },
  { name: "Socket.IO", image: socketioimage },
  { name: "VS Code", image: vscodeimage },
];

export default skillsDetails;
